spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: vishnu@2000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create

  liquibase:
    change-log: classpath:/db.changelog/liquibase-changelog.yaml
    enabled: true